name: Weekly check all Markdown links

on:
  schedule:
<<<<<<< HEAD
    - cron: "0 12 * * 4"
=======
    # Cron for every Monday at 12:00 UTC.
    - cron: "0 12 * * 1"
>>>>>>> v1.5.7

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  markdown-link-check:
    name: Broken Links
<<<<<<< HEAD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
=======
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.4, release-1.3 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
        with:
          ref: ${{ matrix.branch }}
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # tag=v1
>>>>>>> v1.5.7
        with:
          use-quiet-mode: 'yes'
          config-file: .markdownlinkcheck.json
